### ISSUE TITLE
Vortex keeps breaking

### ISSUE THREAD

**Issue by MPritsch** [pikdum/steam-deck#65]
So I've been using this tool for 3 days. In that time vortex broke immediately after the first relaunch. Looked at fixes and saw somewhere to reinstall vortex with this executable: `/home/deck/.pikdum/steam-deck-master/install.desktop`
This does nothing. Only fix I found was to completely uninstall everything with these rm commands:
```bash
# remove these tools
rm -rf ~/.pikdum/
# remove vortex
rm -rf ~/.vortex-linux/
rm -rf ~/.local/share/applications/vortex.*
# manually remove desktop icons
```

Then reinstall using the first bash command and execute the install on the desktop. While this works for the next launch, it broke on the next launch again: The Vortex app will flash up in the icon-bar, then be gone and do nothing.

My next attempt was to reinstall it again, and tell vortex to never update anything. This seemed to work for 2 days. Now on the third day it again won't launch.

Tried to reinstall it with the install.desktop fix, but that does not work.
I honestly can't be bothered to completely reinstall it again. All my configs are gone when I do that: I don't want to setup and download all mods again just to adjust a single thing.

I looked into the log files of vortex. When I properly launches, it will log a bunch of stuff. When it crashed, it will stop after the file validation:

`/home/deck/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Roaming/Vortex/vortex.log`
```
Fri, 12 Jan 2024 17:39:38 GMT - info: --------------------------
Fri, 12 Jan 2024 17:39:38 GMT - info: Vortex Version 1.9.7
Fri, 12 Jan 2024 17:39:38 GMT - info: Parameters C:\Program Files\Black Tree Gaming Ltd\Vortex\Vortex.exe
Fri, 12 Jan 2024 17:39:38 GMT - info: start file validation
```

There is a crash dump which I can't read. In the crash.log it says this:
```
Exception time: 1705080551
Exception code: 80000003
Exception address: 000000014194B996
writing dump C:\users\steamuser\AppData\Roaming\Vortex\temp\dumps\crash-main-1705080549985.dmp
success
```

I have no idea what is broken.

**Comment by pikdum** [comment]
I'm not able to reproduce, but I bumped up the Proton version to the latest.
Try running the update shortcut, that might fix things.

**Comment by MPritsch** [comment]
Thanks for the quick response. I tried to run "install-vortex.desktop" again, but this does not seem to fix it. Do you have any suggestions on how to further troubleshoot the issue?

Otherwise do you know a more stable nexusmod compatible mod-manager for the steam-deck?

Thank you for your work.

**Comment by pikdum** [comment]
You'll want to run `install.sh` to update this tool, not `install-vortex.desktop`.

**Comment by MPritsch** [comment]
Alright tried that just now: Now the "file validation" apparently gets done. Vortex still won't launch or log anything besides that:

```
Sat, 13 Jan 2024 21:43:22 GMT - info: Vortex Version 1.9.12
Sat, 13 Jan 2024 21:43:22 GMT - info: Parameters C:\Program Files\Black Tree Gaming Ltd\Vortex\Vortex.exe
Sat, 13 Jan 2024 21:43:22 GMT - info: start file validation
Sat, 13 Jan 2024 21:43:24 GMT - info: done file validation
```

**Comment by pikdum** [comment]
I'm at a loss then. Have you tried restarting? lol

**Comment by MPritsch** [comment]
I have no idea. But the combination of restarting and reinstalling with the "install-vortex.sh" worked lmao.
Let's see how long it'll last. One thing I noticed, is that the reinstaller throws a bunch of warnings. There are way more for different libs, but you'll get the idea:

```
(wine:4045): GStreamer-WARNING **: 00:29:06.855: Failed to load plugin '/home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstflxdec.so': /home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstflxdec.so: wrong ELF class: ELFCLASS64

(wine:4045): GStreamer-WARNING **: 00:29:06.855: Failed to load plugin '/home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstvideoconvertscale.so': /home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstvideoconvertscale.so: wrong ELF class: ELFCLASS64

(wine:4045): GStreamer-WARNING **: 00:29:06.855: Failed to load plugin '/home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstjpegformat.so': /home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstjpegformat.so: wrong ELF class: ELFCLASS64

(wine:4045): GStreamer-WARNING **: 00:29:06.855: Failed to load plugin '/home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstmpegpsmux.so': /home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstmpegpsmux.so: wrong ELF class: ELFCLASS64

(wine:4045): GStreamer-WARNING **: 00:29:06.855: Failed to load plugin '/home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstadpcmenc.so': /home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstadpcmenc.so: wrong ELF class: ELFCLASS64

(wine:4045): GStreamer-WARNING **: 00:29:06.855: Failed to load plugin '/home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstgeometrictransform.so': /home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstgeometrictransform.so: wrong ELF class: ELFCLASS64

(wine:4045): GStreamer-WARNING **: 00:29:06.855: Failed to load plugin '/home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstvideobox.so': /home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstvideobox.so: wrong ELF class: ELFCLASS64

(wine:4045): GStreamer-WARNING **: 00:29:06.855: Failed to load plugin '/home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstapp.so': /home/deck/.vortex-linux/proton-builds/active/files/lib64/gstreamer-1.0/libgstapp.so: wrong ELF class: ELFCLASS64

```

**Comment by MPritsch** [comment]
FYI the state is repeatable on my steam deck: I just have to switch to Steam-OS gamemode while Vortex is open. This will crash Vortex and it won't launch on the next start

**Comment by Haaroon** [comment]
Mine also breaks

**Comment by SaltyWhaler** [comment]
I had a similar issue happen to mine - not sure what triggered it, but I did a fresh reinstall and after disabling auto-updates in Vortex, it happened again. I think something about disabling auto-updates breaks it.

I was able to fix it without deleting all of my Vortex folders by running the `install-vortex.sh` script. Fingers crossed Vortex trying to update automatically doesn't break it again.

**Comment by papercrane1001** [comment]
Same issue, usually fixed by install-vortex.sh, but now it won't finish opening Vortex at all. I suspect:
The latest deck update
The latest Vortex update
I may have forgotten to close Vortex before going back to game mode last time, too. 

My next intended testing will be to uninstall everything as in first post in this thread and reinstall.

**Comment by pikdum** [comment]
> This will crash Vortex and it won't launch on the next start

Even after rebooting? I'm still having a hard time reproducing this.

**Comment by papercrane1001** [comment]
Yes to the rebooting. To make the order of operations clear, I've tried:
Run Vortex -> fail
Run install-vortex.sh
Run Vortex -> fail
Reboot
Run Vortex -> fail

I think I've also added an additional run of the Run install-vortex before the last Run Vortex, but it's hard to remember. 
I also tried going from a freshly downloaded install.sh, but I'm not so sure of order and rebooting there. 
I can do some testing today, but real organized effort will have to wait for tomorrow.

**Comment by papercrane1001** [comment]
Success with manually uninstalling and then reinstalling. 
Before I re-add all my games and stuff, I'm going to try to intentionally break it to see what happens.

**Comment by papercrane1001** [comment]
Left Vortex open and went to gaming mode via icon, and it broke again.

**Comment by pikdum** [comment]
> If your Vortex state has somehow been corrupted (usually due to anti-virus apps) then you can reset Vortex by deleting or renaming the %appdata%\Vortex folder 

I wonder if this helps?

**Comment by pikdum** [comment]
I'm still not able to reproduce, though. I can get it to break by:

1. open vortex
2. switch to gaming mode
3. switch to desktop mode
4. try to re-open vortex

But restarting is always fixing it for me.

**Comment by pikdum** [comment]
Maybe there's something useful in the Vortex logs?

They're in: `/home/deck/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Roaming/Vortex/`

**Comment by pikdum** [comment]
Or actually:

1. open vortex
2. switch to gaming mode
3. switch to desktop mode
4. try to re-open vortex

This just worked for me. Weird.

Are you on Steam Deck stable, beta, or pre-release?

**Comment by andrewjonesdev** [comment]
I'm having a similar issue. Vortex keeps crashing now and won't open.

**Comment by andrewjonesdev** [comment]
I solves it by downloading the script file install-vortex.sh and running it in the console with bash install-vortex.sh

**Comment by papercrane1001** [comment]
@pikdum Steam Deck stable.  I've attached the vortex.log...
[vortex.log](https://github.com/user-attachments/files/16196572/vortex.log)
Going by the end of the log, it seems to think it loaded properly and exited normally.  I've tried a lot of things now, including a simple and clean restart, but nothing is working to get it open.  Bizarre.  

@andrewjonesdev That gives me:
install-vortex.sh: line 7: syntax error near unexpected token `newline'
install-vortex.sh: line 7: `<!DOCTYPE html>'

**Comment by pikdum** [comment]
Yeah, I'm at a loss here.

**Comment by sxthimons** [comment]
@pikdum Is the version supposed to be 1.13? Because that's what I'm showing is installed.

**Comment by astromediaonly** [comment]
Same here ... not sure if thats the factor but after the latest update it does not start even if I do restart the Deck :/ ... I dont need to use it that much as I did luckily set most of what I needed before it borked completely but its still anoying :) ... hopefully somebody will find the culprit eventually ... indeed it does not seem to be anything usefull in logs :/

**Comment by pikdum** [comment]
Shipped an update that should fix this.

1. run `Update Pikdum's Tools` to get the latest version
2. start `Vortex`
  a. might need to restart

Feel free to re-open if it doesn't.
